### ISSUE TITLE
Corrupted mempped mode file 1200h_output_graph.pbmm

### ISSUE THREAD

**Issue by ntfreddy** [Digital-Umuganda/Deepspeech-Kinyarwanda#1]
I'm very interested in your project but I'm surprised how little information is given to use it. 

I was planning to have a real-time Kinyarwanda speech to Text with your work and I found the following video
https://www.youtube.com/watch?v=c_0Q3T0XYTA and tested your pbmm and scorer models but I'm told that the Model File 1200h_output_graph.pbmm is a correpted memmaped model file.

(DeepSpeech) F:\DeepSpeech\mic_vad_streaming>python mic_vad_streaming.py -m F:\DeepSpeech\1200h_output_graph.pbmm -s "F:\DeepSpeech\kinyarwanda_deepspeech_model(full_vocabulary).scorer"
Initializing model...
INFO:root:ARGS.model: F:\DeepSpeech\1200h_output_graph.pbmm
TensorFlow: v2.3.0-6-g23ad988fcd
DeepSpeech: v0.9.3-0-gf2e9c858
Data loss: Corrupted memmapped model file: F:\DeepSpeech\1200h_output_graph.pbmm Invalid directory offset
Traceback (most recent call last):
  File "mic_vad_streaming.py", line 224, in <module>
    main(ARGS)
  File "mic_vad_streaming.py", line 163, in main
    model = deepspeech.Model(ARGS.model)
  File "F:\DeepSpeech\lib\site-packages\deepspeech\__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

It seems your 1200h_output_graph.pbmm is very small and is text based while other pbmm files such as english deepspeech-0.9.3-models.pbmm are binary and big.

Could you please show us how to test your model?

OS: Windows 10
Python: 3.8.10
DeepSpeech version 0.9.3

**Comment by ntfreddy** [comment]
After installing https://git-lfs.github.com/ If found out that the file1200h_output_graph.pbmm is so huge and the repository is over its data quota.


F:\DeepSpeech>git clone https://github.com/Digital-Umuganda/Deepspeech-Kinyarwanda.git
Cloning into 'Deepspeech-Kinyarwanda'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 102 (delta 20), reused 75 (delta 4), pack-reused 0
Receiving objects: 100% (102/102), 43.44 MiB | 991.00 KiB/s, done.
Resolving deltas: 100% (20/20), done.
Updating files: 100% (58/58), done.
Downloading 1200h_output_graph.pbmm (189 MB)
Error downloading object: 1200h_output_graph.pbmm (58cccb1): Smudge error: Error downloading 1200h_output_graph.pbmm (58cccb154b2c974bc3a444b91d0dce49e381c22d74266b9c86e4ac147a0ffa55): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to F:\DeepSpeech\Deepspeech-Kinyarwanda\.git\lfs\logs\20210822T005037.6886269.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: 1200h_output_graph.pbmm: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ntfreddy** [comment]
This helped me to download the big files https://stackoverflow.com/a/68113604

1. Fork the repo to one of your users
2. Go to repo settings
3. Find "Include Git LFS objects in archives" under the Archives section and check it
4. Go to the Danger Zone section, select "Archive this repository"
5. Confirm and authorize.
6. Return to the archived repository.
7. Download as .zip (Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.)
After my tests found out the accuracy is still low let's contribute to the voice common database in Kinyarwanda.

**Comment by rutsam** [comment]
Thanks @ntfreddy , this project is still under development, the pbmm is trained on 1200 hours but the scorer is still limited, if you have kinyarwanda sentences you can share them to improve the system
